### ISSUE TITLE
Multiple y per register?

### ISSUE THREAD

**Issue by xavicolomer** [adobe/glsl2agal#21]
Hi there,

Thanks for such a great tool!

I am having some problems converting a vertex shader, the original glsl looks like this:

attribute vec2 pos;
            attribute vec4 aVertexColor;

```
        varying vec4 vColor;

        void main(void) {
            gl_Position = vec4(pos.x, pos.y, 0.0, 1.0);
            vColor = aVertexColor;
        }
```

Which translates to:

mov vt0.zw, vc0.xyyy
mov vt0.x, va0.x
mov vt0.y, va0.y
mov op, vt0
mov v0, va1

I am having difficulties to render the triangle with this agal code, although the render works perfectly with this other one:

m44 op, va0, vc0
mov v0, va1

Maybe it's just a newbie mistake.

Thanks!!

**Comment by alexmac** [comment]
Yeah, the problem here is with your shader, not the tool. You appear to be comparing a glsl shader that sets the output position without any transform applied, but the two line agal snippet you are comparing against performs a matrix multiply.

You should be able to mimic that shader with something like:

attribute vec4 vertpos;
uniform mat4 somemat;

void main()
{
gl_Position = somemat \* vertpos
}
